# This file was generated by GoReleaser. DO NOT EDIT.
cask "ensor" do
  version "0.4.3-3"

  on_macos do
    on_arm do
      sha256 "e24721befed21fee781735ad3172304d90efa686eced413d164fdfe7bf528d45"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "351a5c5c4be2ea457fc11fec5fb4de4a7c04f4f91bc0df9f98c3fd271a459845"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a9a4a75d3c224fda3cb107821ea5c2c7b7825f22a34383774ebb75d197e4bf92"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "191d63f0026459af09a1b1e4e766044e5b7a9cbbe7f74eb038b353d988c8a6ee"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Linux_x86_64.tar.gz"
    end
  end

  name "ensor"
  desc "Censor secrets in your code"
  homepage "https://github.com/Pratyay360/ensor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ensor"

  generate_completions_from_executable "ensor", "completion",
    base_name: "ensor",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
