# This file was generated by GoReleaser. DO NOT EDIT.
cask "ensor" do
  version "0.4.3-2"

  on_macos do
    on_arm do
      sha256 "9bf600cdb40b974cab5ddaf31ae3a78e5a65b302c15acf752e91251542ca3d7b"
      url "https://github.com/Pratyay360/ensor/releases/download/v#{version}/ensor_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e1b43a4dee276c3122324d9d59da7d10e4c4879602cb7c408c6d0d25cf2ceca5"
      url "https://github.com/Pratyay360/ensor/releases/download/v#{version}/ensor_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ff9aa1d181a5acce356f7d1757ac020eaec5ddf34cc5988ad2cc61a43a055589"
      url "https://github.com/Pratyay360/ensor/releases/download/v#{version}/ensor_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1ae598c2cda6603a31d56ffe5fdaceb506a44335c7618da6d81f1177b14756f5"
      url "https://github.com/Pratyay360/ensor/releases/download/v#{version}/ensor_Linux_x86_64.tar.gz"
    end
  end

  name "ensor"
  desc "Censor secrets in your code"
  homepage "https://github.com/Pratyay360/ensor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ensor"

  generate_completions_from_executable "ensor", "completion",
    base_name: "ensor",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
