# This file was generated by GoReleaser. DO NOT EDIT.
cask "ensor" do
  version "0.4.5"

  on_macos do
    on_arm do
      sha256 "f35487e2dcb9ea685205aa51f5b026375bb592c118dc191899e5fb8b8250f878"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e8e7305d97a7b99c16dcf373314697175849eb07a7051b2a8613546ba79bdec7"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2a7fb89d28ce586e3ddb4abaf83902491ccc892f465d45f93c9999d65e78e905"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c28a76e356491f8b88792b0ed1bdd6f938496d50b776f8c84c2c9680b5fbf697"
      url "https://github.com/Pratyay360/ensor/releases/download/#{version}/ensor_Linux_x86_64.tar.gz"
    end
  end

  name "ensor"
  desc "Censor secrets in your code"
  homepage "https://github.com/Pratyay360/ensor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ensor"

  generate_completions_from_executable "ensor", "completion",
    base_name: "ensor",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
