# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgit-cli" do
  version "0.3.3-0"

  on_macos do
    on_arm do
      sha256 "1924d11d857a4af0feb6df99b88be1b771ed52861f52c2eadbfc6f40690e8fa5"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3224b79c613ec58e919dfefb48ec89876b394dfd995127ba0ea53e4c01c01455"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "30b0ce7b868ec0804fe730a4349c6c265a7d4c3e3ab6f8ce783d847168efbe50"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7eb5224fbdbd028ed0b410b21c9dceba7f940e5f2f3cc68b3b890ad642d70d7a"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_x86_64.tar.gz"
    end
  end

  name "forgit-cli"
  desc "A simple git helper"
  homepage "https://github.com/Pratyay360/forgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgit"

  generate_completions_from_executable "forgit", "completion",
    base_name: "forgit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
