# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgit" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "7142a551f9f8ac74058def31ae50083a822686ba67b6ce465c11c555bfa922f2"
      url "https://github.com/pratyay360/forgit/releases/download/v#{version}/forgit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f33736d50bf2f8c6937b93e2c2130e49008f5a660427d6ebf77fdcde1cb5923f"
      url "https://github.com/pratyay360/forgit/releases/download/v#{version}/forgit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "437664c2ca423690d9996249bce288b57bf32cdd21681252dfa747fd74302984"
      url "https://github.com/pratyay360/forgit/releases/download/v#{version}/forgit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d17e07f2237dd4a1616e24c8dd45313e2e6967ff7353e36fb7b981ad23c89686"
      url "https://github.com/pratyay360/forgit/releases/download/v#{version}/forgit_Linux_x86_64.tar.gz"
    end
  end

  name "forgit"
  desc "A simple git helper"
  homepage "https://github.com/pratyay360/forgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgit"

  generate_completions_from_executable "forgit", "completion",
    base_name: "forgit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
