# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgit" do
  version "0.3.4"

  on_macos do
    on_arm do
      sha256 "07d2ee34a7786de2fa7b46c88cc77ad3f285dc54b4649c3f70dbff3d062384e4"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "162a8c61da92c19c1594a0c970413f6843d7c031119193189125c7fbac85cebc"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4aa3856dc96c5893e0bfb8f94e1b6ca46452d95f61f6f6c40381e5b8a92f8f39"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4b56ff116f082dde1b55d656ce1eacae859545c925abc505cb9b4dcc597a1d73"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_x86_64.tar.gz"
    end
  end

  name "forgit"
  desc "A simple git helper"
  homepage "https://github.com/Pratyay360/forgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgit"

  generate_completions_from_executable "forgit", "completion",
    base_name: "forgit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
