# This file was generated by GoReleaser. DO NOT EDIT.
cask "forgit" do
  version "0.3.6"

  on_macos do
    on_arm do
      sha256 "ee1361331cbc1d2b2d85305005bcbfab9571855a58e705502b014a753062aacf"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ce6d0e832f53faa0d70e6b49808cb5381d161f811e9488ad719ef1071436ab79"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "70b8dfaa4228d88bbb97bfa36c29e80ec10a4a1211db092a667455b34667d8f4"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8ee919079ecdb810a353bb79ef5ee7c4b6daca32d48fa2c83aa446a2979f8548"
      url "https://github.com/Pratyay360/forgit/releases/download/#{version}/forgit_Linux_x86_64.tar.gz"
    end
  end

  name "forgit"
  desc "A simple git helper"
  homepage "https://github.com/Pratyay360/forgit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "forgit"

  generate_completions_from_executable "forgit", "completion",
    base_name: "forgit",
    shell_parameter_format: :cobra,
    shells: [:bash, :zsh, :fish]

  # No zap stanza required
end
