# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox-export" do
  version "0.1.0-q"

  on_linux do
    on_arm do
      sha256 "ff222398c0cbf96fd4cd56465d2e1c189b687dabd7afb2dcc36015837fe87af0"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b21345237dd0a4d21dcca29b1ce87b4c62c64c2d1d2c3fee0a43a8dd8d6536da"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_x86_64.tar.gz"
    end
  end

  name "toolbox-export"
  desc "Make applications installed inside Toolbx containers available on the host"
  homepage "https://github.com/Pratyay360/toolbox-export"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox-export"

  # No zap stanza required
end
