# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox-export" do
  version "0.1.0-r"

  on_linux do
    on_arm do
      sha256 "9778a7b985215ec57d2e1278aeabab516a22cb525bf8fe1bcba49d1a4a08c6c8"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b04acac5bbb33c37d739b1812dc8db8e2a90c2d81dcfb286ae17883f7a5321e3"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_x86_64.tar.gz"
    end
  end

  name "toolbox-export"
  desc "Make applications installed inside Toolbx containers available on the host"
  homepage "https://github.com/Pratyay360/toolbox-export"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox-export"

  # No zap stanza required
end
