# This file was generated by GoReleaser. DO NOT EDIT.
cask "toolbox-export" do
  version "0.1.0-s"

  on_linux do
    on_arm do
      sha256 "26639a43605609e41d2ab20e1e89b9eb05ee9e05541df09a2284710314c64a38"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "006569c7f95d8e31911e8cbd23cd1c9fee9fd5cc67f67cf89f20b1a66f30525b"
      url "https://github.com/Pratyay360/toolbox-export/releases/download/v#{version}/toolbox-export_Linux_x86_64.tar.gz"
    end
  end

  name "toolbox-export"
  desc "Make applications installed inside Toolbx containers available on the host"
  homepage "https://github.com/Pratyay360/toolbox-export"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "toolbox-export"

  # No zap stanza required
end
