name: check update

on:
  schedule:
    - cron: "0 2 */2 * *"
  workflow_dispatch:
  pull_request:
  push:

permissions:
  contents: write
  actions: write
  pull-requests: write

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Set up Homebrew (no sudo)
        env:
          HOMEBREW_NO_ENV_HINTS: "1"
          HOMEBREW_NO_INSTALL_CLEANUP: "1"
          HOMEBREW_NO_ANALYTICS: "1"
          HOMEBREW_NO_AUTO_UPDATE: "1"
        run: |
          set -euo pipefail
          brew --version
          brew update

      - name: Tap custom repo
        run: brew tap ${{ github.repository_owner }}/homebrew-tap

      - name: Get latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_NO_ENV_HINTS: "1"
          HOMEBREW_NO_INSTALL_CLEANUP: "1"
          HOMEBREW_NO_ANALYTICS: "1"
          HOMEBREW_SUDO_ACCESS: "0"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          casks=$(brew livecheck --json $(brew search "${{ github.repository_owner }}/homebrew-tap") | jq '.[].cask')
          for cas in $casks; do
            cask=$(echo "$cas" | tr -d \"\')
            should_bump="$(brew livecheck --json $cask | jq -r '.[].version.outdated')"
            if [ "$should_bump" = "true" ]; then
              brew bump-cask-pr --commit --write-only $cask --version "$(brew livecheck --json $cask | jq -r '.[].version.latest')"
            fi
          done
          git add . && git commit -m "Update casks" && git push
